[package]
name = "pallet-contracts-mock-network"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
description = "A mock network for testing pallet-contracts"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [ "derive", "max-encoded-len"] }

frame-support = { path = "../../support", default-features = false}
frame-system = { path = "../../system", default-features = false}
pallet-assets = { path = "../../assets" }
pallet-balances = { path = "../../balances" }
pallet-contracts = { path = ".." }
pallet-contracts-primitives = { path = "../primitives", default-features = false}
pallet-contracts-proc-macro = { path = "../proc-macro" }
pallet-insecure-randomness-collective-flip = { path = "../../insecure-randomness-collective-flip" }
pallet-message-queue = { path = "../../message-queue" }
pallet-proxy = { path = "../../proxy" }
pallet-timestamp = { path = "../../timestamp" }
pallet-utility = { path = "../../utility" }
pallet-xcm = { path = "../../../../polkadot/xcm/pallet-xcm", default-features = false}
polkadot-parachain-primitives = { path = "../../../../polkadot/parachain"  }
polkadot-primitives = { path = "../../../../polkadot/primitives"  }
polkadot-runtime-parachains = {path = "../../../../polkadot/runtime/parachains"}
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
sp-api = { path = "../../../primitives/api", default-features = false}
sp-core = { path = "../../../primitives/core", default-features = false}
sp-io = { path = "../../../primitives/io", default-features = false}
sp-keystore = { path = "../../../primitives/keystore" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false}
sp-std = { path = "../../../primitives/std", default-features = false}
sp-tracing = { path = "../../../primitives/tracing" }
xcm = { package = "staging-xcm", path = "../../../../polkadot/xcm", default-features = false}
xcm-builder = {package = "staging-xcm-builder", path = "../../../../polkadot/xcm/xcm-builder"}
xcm-executor = { package = "staging-xcm-executor", path = "../../../../polkadot/xcm/xcm-executor", default-features = false}
xcm-simulator = {path = "../../../../polkadot/xcm/xcm-simulator"}

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-proc-macro/full",
	"pallet-contracts/std",
	"pallet-insecure-randomness-collective-flip/std",
	"pallet-proxy/std",
	"pallet-timestamp/std",
	"pallet-utility/std",
	"pallet-xcm/std",
	"scale-info/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
]

